name: Update China IP Ruleset

on:
  schedule:
    - cron: '0 0 * * *'  # 每天UTC 00:00 (北京时间 08:00) 运行
  workflow_dispatch:  # 允许手动触发

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
      
      - name: Download and merge China IP lists
        run: python download_ip_lists.py
      
      - name: Create ruleset JSON
        run: python create_ruleset.py
      
      - name: Download and compile with sing-box
        run: python download_and_compile.py
      
      - name: Push to rule-set branch
        run: python git_push_ruleset.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
